### ISSUE TITLE
Remove storage of ExecutionData in message receiver

### ISSUE THREAD

**Issue by ermyas** [MultiMessageAggregation/multibridge#35]
Currently, the `MultiBridgeMessageReceiver` stores the full execution parameters of each unique message as a map of `ExecutionData` structs. A more efficient alternative is to store only the hash of these values and require the caller to provide the details when calling `executeMessage()`. The provided details would then be hashed and compared against the stored hash for the message before execution.

**Comment by xiaozhou** [comment]
Potential optimization: Do not store `ExecutionData` in the msg receiver contract. Only store the hash of all fields instead.
